/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author karan
 */
public class issuebook extends javax.swing.JFrame {

    /**
     * Creates new form issuebook
     */
    public issuebook() {
        initComponents();
        Date dNow = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyyMMdd");
        String reportDate = ft.format(dNow);
        txtissuedate.setText(reportDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttitle = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        txtstudID = new javax.swing.JTextField();
        txtstudname = new javax.swing.JTextField();
        txtstudclass = new javax.swing.JTextField();
        txtissuedate = new javax.swing.JTextField();
        btnissuebook = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("ISSUE BOOK");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Book Title:");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Book Author:");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Student Roll NO:");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Student Name:");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("Student Class:");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("Date Of Issue:");

        txtstudname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudnameActionPerformed(evt);
            }
        });

        btnissuebook.setBackground(new java.awt.Color(0, 255, 255));
        btnissuebook.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnissuebook.setForeground(new java.awt.Color(0, 153, 0));
        btnissuebook.setText("Issue Book");
        btnissuebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissuebookActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(51, 255, 255));
        btnback.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 0, 0));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnissuebook)
                                .addGap(79, 79, 79)
                                .addComponent(btnback))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttitle, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(txtauthor)
                                    .addComponent(txtstudID)
                                    .addComponent(txtstudname)
                                    .addComponent(txtstudclass)
                                    .addComponent(txtissuedate)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtstudID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtstudname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstudclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtissuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnissuebook)
                    .addComponent(btnback))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtstudnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudnameActionPerformed

    private void btnissuebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissuebookActionPerformed
        String title=txttitle.getText();
        String author=txtauthor.getText();
        int StudID=Integer.parseInt(txtstudID.getText());
        String StudName = txtstudname.getText();
        String StudClass = txtstudclass.getText();
        int IssueDate=Integer.parseInt(txtissuedate.getText());
        boolean status=false,studStatus=false;
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb36", "root", "123");
            PreparedStatement ps=con.prepareStatement("select * from books where title="+title+" and author="+author);
            ps.setString(1,title);
            ps.setString(2,author);
            ResultSet rs=ps.executeQuery();
            status=rs.next();
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        if(status)
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb36", "root", "123");
                PreparedStatement ps=con.prepareStatement("select * from student where id ="+StudID+"");
//PreparedStatement ps=con.prepareStatement("select * from Student where ID =?,Name=?,Class=?");
//ps.setInt(3,StudID);
//ps.setString(4,StudName);
//ps.setString(5,StudClass);
                ResultSet rs=ps.executeQuery();
                studStatus=rs.next();
                con.close();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        if(studStatus)
        {
            int No_Copies=0, Issued_No=0;
            int status1= 0;
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb36", "root", "123");
                PreparedStatement ps=con.prepareStatement("select no_of_copies,issued_no from books where title="+title+" and author ="+author+"");
// ps.setString(1,title);
// ps.setString(2,author);
                ResultSet rs=ps.executeQuery();
                if(rs.next())
                {
                    Issued_No=rs.getInt("Issued_No");
                    No_Copies=rs.getInt("No_Copies");
                }
                if(No_Copies>0 && No_Copies > Issued_No)
                {
                    int tempNo = No_Copies-1;
                    int tempIssNo = Issued_No+1;
                    PreparedStatement ps2=con.prepareStatement("update books set issued_no="+tempIssNo+",no_of_copies= "+tempNo+" where title='"+title+"' and author ='"+author+"'");
                    status1=ps2.executeUpdate();
                }
                con.close();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            
        }
            //if(status1>0)
            //{
                try
                {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testdb36", "root", "123");
                    PreparedStatement ps=con.prepareStatement("insert into issuebooks values(?,?,?,?,?,?)");
                    ps.setString(1,title);
                    ps.setString(2,author);
                    ps.setInt(3,StudID);
                    ps.setString(4,StudName);
                    ps.setString(5,StudClass);
                    ps.setInt(6,IssueDate);
                    int i =ps.executeUpdate();
                    if(i>0)
                    {
                        JOptionPane.showMessageDialog(issuebook.this,"Book issued successfully!");
                        Librariansection.main(new String[]{});
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(issuebook.this,"Sorry, unable to issue!");
                    }//end of save if-else
                    con.close();
                }
                catch(Exception e)
                {
                    //System.out.println(e);
                }
            //}
        //}
    
    
    }//GEN-LAST:event_btnissuebookActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        Librariansection.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issuebook().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnissuebook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtstudID;
    private javax.swing.JTextField txtstudclass;
    private javax.swing.JTextField txtstudname;
    private javax.swing.JTextField txttitle;
    // End of variables declaration//GEN-END:variables
}
