/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagment;

/**
 *
 * @author karan
 */
public class Librariansection extends javax.swing.JFrame {

    /**
     * Creates new form Librariansection
     */
    public Librariansection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnaddstud = new javax.swing.JButton();
        btnaddbook = new javax.swing.JButton();
        btnviewbook = new javax.swing.JButton();
        btnreturnbook = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnissuebook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("LIBRARIAN SECTION");

        btnaddstud.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnaddstud.setForeground(new java.awt.Color(0, 153, 51));
        btnaddstud.setText("ADD STUDENT");
        btnaddstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddstudActionPerformed(evt);
            }
        });

        btnaddbook.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnaddbook.setText("ADD BOOKS");
        btnaddbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbookActionPerformed(evt);
            }
        });

        btnviewbook.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnviewbook.setForeground(new java.awt.Color(51, 51, 255));
        btnviewbook.setText("VIEW BOOKS");
        btnviewbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewbookActionPerformed(evt);
            }
        });

        btnreturnbook.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnreturnbook.setForeground(new java.awt.Color(255, 51, 255));
        btnreturnbook.setText("RETURN BOOK");
        btnreturnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnbookActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(51, 255, 255));
        btnlogout.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(204, 0, 0));
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        btnissuebook.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnissuebook.setForeground(new java.awt.Color(255, 51, 204));
        btnissuebook.setText("ISSUE BOOKS");
        btnissuebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissuebookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnaddbook, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnaddstud, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnviewbook, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnissuebook, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnreturnbook)
                            .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnaddstud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnaddbook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnviewbook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnissuebook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnreturnbook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlogout)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        LibrarySystemApp.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnaddstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddstudActionPerformed
        StudentInfo.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btnaddstudActionPerformed

    private void btnaddbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbookActionPerformed
        addbooks.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btnaddbookActionPerformed

    private void btnviewbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewbookActionPerformed
        viewbooks.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btnviewbookActionPerformed

    private void btnreturnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnbookActionPerformed
        returnbook.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btnreturnbookActionPerformed

    private void btnissuebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissuebookActionPerformed
        issuebook.main(new String[]{});
        this.dispose();
    }//GEN-LAST:event_btnissuebookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librariansection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librariansection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librariansection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librariansection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librariansection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddbook;
    private javax.swing.JButton btnaddstud;
    private javax.swing.JButton btnissuebook;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnreturnbook;
    private javax.swing.JButton btnviewbook;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
